name: deploy
on:
  push:
    branches:
      - main
jobs:
  github-pages:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Yarn
        run: npm install --location=global yarn

      - name: Install dependencies
        run: yarn

      - name: Build src
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Commit and push changes to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist
          echo > .nojekyll

          git init
          git checkout -b gh-pages
          git add -A
          git commit -m 'ci: deploy'

          git remote add origin https://sparkbox:$GITHUB_TOKEN@github.com/sparkbox/sparkeats.git

          git push --force origin gh-pages:gh-pages
